name = "backend"
type = "javascript"
account_id = "c5bc78d0b867fc8bac8435761e50d993"
workers_dev = true
route = ""
zone_id = ""

[vars]
API_URL = "https://laid-backend.pamu.me"
SUPABASE_URL = "https://ygggayldbzezqqsunqdd.supabase.co"
SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyODQyMzg3NCwiZXhwIjoxOTQzOTk5ODc0fQ.8dFMJxk51smLydcuXwtmrwYztTHuRDqe6VKpzH-yY3g"

[build.upload]
format = "service-worker"


[miniflare]
host = "127.0.0.1"                 ## --host
port = 8787                        ## --port
